export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_LOADING ="ADD_TO_CART_LOADING";
export const ADD_TO_CART_ERR="ADD_TO_CART_ERR";

export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_CART_LOADING ="CLEAR_CART_LOADING";
export const CLEAR_CART_ERR="CLEAR_CART_ERR";


export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const REMOVE_FROM_CART_LOADING ="REMOVE_FROM_CART_LOADING";
export const REMOVE_FROM_CART_ERR="REMOVE_FROM_CART_ERR";

export const INC_CART ="INC_CART";
export const INC_CART_LOADING ="INC_CART_LOADING";
export const INC_CART_ERR ="INC_CART_ERR";


export const DEC_CART ="DEC_CART";
export const DEC_CART_LOADING ="DEC_CART_LOADING";
export const DEC_CART_ERR ="DEC_CART_ERR";

export const GET_CART="GET_CART";
export const GET_CART_LOADING="GET_CART_LOADING";
export const GET_CART_ERR="GET_CART_ERR";

export const ADD_ODER_HISTORY="ADD_ODER_HISTORY";
export const ADD_ODER_HISTORY_LOADING="ADD_ODER_HISTORY_LOADING";
export const ADD_ODER_HISTORY_ERR="ADD_ODER_HISTORY_ERR";

export const GET_ODER_HISTORY="GET_ODER_HISTORY";
export const GET_ODER_HISTORY_LOADING="GET_ODER_HISTORY_LOADING";
export const GET_ODER_HISTORY_ERR="GET_ODER_HISTORY_ERR";

export const CHECK_OUT="CHECK_OUT";
export const CHECK_OUT_LOADING="CHECK_OUT_LOADING";
export const CHECK_OUT_ERR="CHECK_OUT_ERR";